
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const ADD_USER = 'ADD_USER';
export type ADD_USER = typeof ADD_USER;

export const DELETE_USER = 'DELETE_USER';
export type DELETE_USER = typeof DELETE_USER;

export const TOGGLE_ADMIN = 'TOGGLE_ADMIN';
export type TOGGLE_ADMIN = typeof TOGGLE_ADMIN;

export const LOADED_USERS = 'LOADED_USERS';
export type LOADED_USERS = typeof LOADED_USERS;

export const FETCH_USERS = 'FETCH_USERS';
export type FETCH_USERS = typeof FETCH_USERS;
